### ISSUE TITLE
对于大文件的一些想法

### ISSUE THREAD

**Issue by huangguiniab** [RxinnotRstar/Rxinns-video-museum#6]
github的大文件限制好像是100M来着，理论上最大可以上传99兆的文件

可是比如下面这个分卷
[Rxinns-video-museum/哲♂学/鬼畜视频/泽野螳螂-包青天.zip.001](https://github.com/RxinnotRstar/Rxinns-video-museum/blob/main/%E5%93%B2%E2%99%82%E5%AD%A6/%E9%AC%BC%E7%95%9C%E8%A7%86%E9%A2%91/%E6%B3%BD%E9%87%8E%E8%9E%B3%E8%9E%82-%E5%8C%85%E9%9D%92%E5%A4%A9.zip.001) 
解压出来只有88兆，符合上传标准，我认为应该解压保存，这样才能降低传播成本和方便二次创作

**Comment by RxinnotRstar** [comment]
我这边因为不擅长使用工具，因此我只有能力上传最大50MB的文件。请问您可以帮我用pull request 功能转换成原文件吗？谢谢！

**Comment by huangguiniab** [comment]
建议翻墙后使用Github，毕竟连接十分不稳定。墙内的网络每隔几分钟能用一下github，和被半墙了差不多

如果懒得翻墙建议使用SSH连接github，就算网页无法访问，SSH仍然可以操作。我是联通用户，用SSH访问挺稳定的。百度有用SSH连接到Github的教程，你可以试一下

**Comment by huangguiniab** [comment]
新pr在 #7

**Comment by RxinnotRstar** [comment]
谢谢！
